### ISSUE TITLE
Didn't find all todos

### ISSUE THREAD

**Issue by jpenna** [reergymerej/todo#29]
I don't know what the problema might be, but I just installed it and it got todos from just one folder.
Screenshot attached and TODO highlighted
![todo](https://cloud.githubusercontent.com/assets/16005946/22383326/6f003524-e4b0-11e6-8493-fee1ef7aac47.png)

**Comment by reergymerej** [comment]
@jpenna Judging by the other results, it looks like you're searching using the [default regex](https://github.com/reergymerej/todo/blob/master/lib/todo.js#L19).  The `TODO` in your screenshot doesn't have the trailing `:`, so it won't match.  Can you confirm this, please?

**Comment by reergymerej** [comment]
Please reopen if this is an issue.
