### ISSUE TITLE
(IDEA) Add more categorie

### ISSUE THREAD

**Issue by BellemareMederic** [reergymerej/todo#33]
Its very nice to work whit Todo but i use other comments mark ... like FIXME BUG IDEA and other can you add categorie on this ?

http://prntscr.com/fh97gg

**Comment by 10halec** [comment]
@BellemareMederic Just add the tags you want to the RegExp Pattern under settings. It defaults to `TODO:`


    (TODO:|FIXME:|CHANGED:|XXX:|IDEA:|HACK:| NOTE:|REVIEW:|NB:|BUG:).+

**Comment by itotallyrock** [comment]
That should be a default though.  At least include all the tags used in the atom official todo language.

**Comment by jonatjano** [comment]
In my fork I've changed the default regex to target the tags of language-TODO. I'll make a PR when I've accomplished my goal (see #38)
