### ISSUE TITLE
Don't search .gitIgnore entries.

### ISSUE THREAD

**Issue by cairin** [reergymerej/todo#36]
- [ ] Add a button in config to allow the user to choose whether they want to search directories/files in a projects .gitIgnore
- [ ] Parse and add .gitIgnore file entries to `todo.c_ignorePaths` so that they are automatically ignored.

**Comment by reergymerej** [comment]
Thanks for the suggestions @cairinmichie!  Would you be interested in submitting a PR for either of these?

**Comment by cairin** [comment]
If I get time. Not sure I will anytime soon though so don't assign it to me.
