### ISSUE TITLE
use a templating engine or atom view

### ISSUE THREAD

**Issue by reergymerej** [reergymerej/todo#6]
The current view is created pretty painfully.  Figure out what others are using (not space pen) to create the view.

**Comment by reergymerej** [comment]
space-pen seems to be the de facto way

**Comment by reergymerej** [comment]
I don't care if everyone else is using JS to create their views.  That's silly.  created 0.3.0-html to try a Kendo-ish way (f25c0bc015cc89e6d42d5b7d9b3120ce12a515fb)

**Comment by kanekotic** [comment]
hi @reergymerej , i see you have the same issue as me, any findings?

i found this two posts if you are interested:
[trying to decide a template framework for atom](https://github.com/atom/atom/issues/5756)
[first discussion on how to do templates in atom](https://github.com/atom/atom/issues/3752)

**Comment by reergymerej** [comment]
Thanks, @kanekotic. I'll check it out.

**Comment by reergymerej** [comment]
@kanekotic I tried rolling my own (easy-view) and using it in another branch, but I got sidetracked. Check it out and let me know what you think.

**Comment by kanekotic** [comment]
sorry for the late reply...but it was quite busy times.

It looks cool, but my main concern is how can you bind data to be displayed two-way bindings for user inputs (imagine you want to add a filters to your todos). Atom tends to not work at all fine with input boxes and how to bind the internal value of a atom-text-editor dosnt look to be straight forward.

**Comment by reergymerej** [comment]
Thanks for the feedback. Easy view was just for simple one way bindings. Let me know if you find something that works.

**Comment by kanekotic** [comment]
hi again @reergymerej i have done all i wanted finally with vue-js there are a few downsides on the compatibility with atom but i could work around those in an "easy" and "clean" way. Here a fast resume and workarounds and lessons learned:
- declaring a view and a view model is really easy, and atom accepts the html input without any issue.
- Bindings are straight forward
- 'atom-text-editor' is not binding friendly, i used then 'input class="native-key-bindings"' and styled it as a atom-text-editor. (this was done thanks to some advice given by @lee-dohm and @pamtbaau)
-List binding ('li') is not friendly to empty arrays, so you might need to pre-populated to a fake object of the result and the fields.  

So this are my findings. To try this i created a package for atom (search and play videos of youtube in atom) you can se the code [here](https://github.com/Hatisoft/playyoutube-atom). Let me know what you think. my javascript/coffescript might be a little bit rusty (i accept any comments and advice on my coding).
